CUSTOM_ADMIN/urls.py
from django.urls import path
from . import views
app_name = "custom_admin" 

urlpatterns = [
     path('', views.dashboard1, name='dashboard1'),


    

     # Jobs CRUD
     path('jobs/', views.joblist, name = 'jobs_list'),
     path('jobs/add/', views.job_add, name = 'job_add'),
     path('jobs/edit/<int:job_id>/', views.job_edit, name = 'job_edit'),
     path('jobs/del/<int:job_id>/', views.job_del, name = 'job_del'),


     # Applications
     path('application/', views.all_applications, name = 'app_list'),
     path('del/<int:pk>/', views.delete, name = 'del_app'),

     # Users
     path('users/', views.userlist, name = 'user_list'),
   

]

JOBFORM/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from .views import CustomLoginView
from django.contrib.auth.decorators import login_required

urlpatterns = [

    # ALL JOB POST
    path('job/', login_required(views.job_list), name='job_list'),
    # JOB DETAIL
    path('job/<int:pk>/', login_required(views.job_detail), name='job_detail'),
    path('about/', login_required(views.about), name='about'),
    path('del/<int:pk>/', views.delete, name='delete'),
    path('applications/<int:pk>/pdf/', views.application_pdf, name = 'application_pdf'),



    #ADMIN PAGE
    path('applications/', views.all_applications, name= 'all_applocations'),


    

    # AUTH URLS
    path('signup/', views.signup, name='signup'), 
    path('', RedirectView.as_view(url='/accounts/login/', permanent=False)),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', views.customlogout, name= 'logout'),
 ] 

JOBPROJECT/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from JOBFORM import views


urlpatterns = [
    path('admin/', admin.site.urls),
   path("myadmin/", include("CUSTOM_ADMIN.urls", namespace="custom_admin")),


    path('', include('JOBFORM.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CUSTOM_ADMIN/models.py
from django.db import models

# Create your models here.

CUSTOM_ADMIN/forms.py
from django import forms
from JOBFORM.models import JobPost

class JobPostForm(forms.ModelForm):
    class Meta:
        model = JobPost
        fields = '__all__'

        widgets = {

            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Title'}),
            'company':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter The Company Name'}),
            'location':forms.TextInput(attrs={'class':'form-control'}),
            'job_type':forms.TextInput(attrs={'class':'form-control'}),
            'salary':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control'}),
            'requirements':forms.Textarea(attrs={'class':'form-control'}),
        }

CUSTOM_ADMIN/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User  
from JOBFORM.models import JobApplication,JobPost
from .forms import JobPostForm
from django.contrib import messages  

# Create your views here.
# CUSTOM ADMIN.............................

def superuser_required(view_func):
    return user_passes_test(lambda u: u.is_superuser)(view_func)

@superuser_required
def userlist(request):
    users = User.objects.all()
    
    return render(request, "custom_admin/user_list.html", {'users': users})  



# ----- Jobs -----

@superuser_required
def joblist(request):
    jobs = JobPost.objects.all()
    return render(request, 'custom_admin/job_list.html', {'jobs':jobs})


@superuser_required
def job_add(request):
    Add = JobPost.objects.all()
    if request.method == 'POST':
        form = JobPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('job_list')
    else:
        form = JobPostForm()
    return render(request, 'custom_admin/job_form.html', {'form': form, 'Add': Add})


@superuser_required
def job_edit(request, job_id):
    job = JobPost.objects.get(id=job_id)
    if request.method == 'POST':
        form = JobPostForm(request.POST, request.FILES, instance=job)
        if form.is_valid():
            form.save()
            return redirect('custom_admin:jobs_list')
    else:
        form = JobPostForm(instance=job)
    return render(request, 'custom_admin/job_form.html', {'form': form, 'job':job})


@superuser_required
def job_del(request,job_id):
    job = JobPost.objects.get(id=job_id)
    job.delete()
    return redirect('custom_admin:jobs_list')
    







@superuser_required
def all_applications(request):
    app = JobApplication.objects.all().order_by('-applied_on')    
    return render (request, 'custom_admin/app_list.html', {'app':app})

def delete(request,pk):
    form = JobApplication.objects.get(pk=pk)
    form.delete()
    return redirect('/myadmin/application/')




# Dashboard
@superuser_required
def dashboard1(request):
    jobs_count = JobPost.objects.count()
    apps_count = JobApplication.objects.count()
    users_count = User.objects.count()
    return render(request, 'custom_admin/dashboard.html', {
        'jobs_count': jobs_count,
        'apps_count': apps_count,
        'users_count': users_count
    })   

CUSTOM_ADMIN/templates/custom_admin/app_list.html
{% extends "custom_admin/dashboard.html" %}

{% block head %}

<style>
    table {

        text-transform: uppercase;    
    }


    .table thead th{
        background-color: #3F007A;
        color: #fff;
    }

    .container{
        margin-top: 6dvh;
    }

    .table{
     border-radius: 12px;        /* Round table corners */
    overflow: hidden;           /* Ensures header/rows follow rounding */
    border: 1px solid #ddd;
    }

    td a{
    color: #3F007A;
    text-decoration: none;
        
    }
    td a:hover{
        color: black;
        font-weight: 600;
    }

   
  
</style>
{% endblock %}



    

{% block work %}
<div class="container">
    <div class="app"><h2>All Applications</h2></div>
<div class="table-responsive ">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>PHOTO</th>
                <th>NAME</th>
                <th>JOB</th>
                
                <th>APPLIED ON</th>
                <th>RESUME</th>
                <th>INFO</th>
                <th>DELETE</th>

            </tr>
        </thead>
        <tbody>
            {% for x in app %}
            <tr>
                <td>{% if x.profile_photo %}
                    <a href="{{x.profile_photo.url}}" download> <img src="{{x.profile_photo.url}}" width="50"
                            height="50" download> </a>
                    {% else %}
                    No File
                    {% endif %}
                </td>
                <td>{{x.full_name}}</td>
                <td>{{x.job.title}}</td>
                
                <td>{{x.applied_on}}</td>

                <td>{% if x.resume %}
                    <a href="{{x.resume.url}}" download> DOWNLOAD </a>
                    {% else %}
                    No File
                    {% endif %}</td>

                <td> 
                    <a href="/applications/{{x.pk}}/pdf/">PDF</a>
                </td>
                <td><a class="btn btn-danger " href="{% url 'custom_admin:del_app' x.pk %}">DELETE</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


</div>


{% endblock %}

CUSTOM_ADMIN/templates/custom_admin/dashboard.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
     <title>My Custom Admin</title>
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>

<style>
    html, body{
        height: 100%;
    }

     header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem 2rem;
        background-color: #3F007A;
        border-bottom: 4px solid rgb(15, 14, 14);
        position: sticky;
        top: 0;
        z-index: 1000;
        margin-bottom: 6vh;
    }

    .logo {
        color: #fff;
        
        font-size: 1.0rem;
        letter-spacing: 1px;
    }

    .job-head nav ul {
        list-style: none;
        display: flex;
        gap: 1.5rem;
        margin: 0;
        padding: 0;
    }

    .job-head nav a {
        text-decoration: none;
        font-weight: 500;
        color: white;
        transition: color 0.3s ease;
    }

    .job-head nav a:hover {
        color: rgb(2, 2, 2);
    }

    .job-head nav .btn:hover {
        color: black;
    }

    /* Make logout consistent */
    .job-head nav .btn {
        padding: 0.4rem 0.9rem;
        border-radius: 20px;
        font-size: 0.9rem;
    }

    .card{
        background-color: #3F007A;
    }

  #btn-logout:hover{
     background: rgb(111, 66, 193);  /* Fill purple on hover */
     color: #fff;                    
  }

   
</style>

<body style="background-color: rgb(169, 190, 216); height: 100;">



  <header class="job-head">
        <div class="logo"> HI! ANIKET, WELCOME BACK</div>
        <div class="navbar">
            <nav>
                <ul>
                    <li><a href="/myadmin/">HOME</a></li>
                    <li><a href="/about/">ABOUT</a></li>
                    <li><a class="btn btn-outline-primary ms-3" id="btn-logout"  href="/logout/">
                        LOGOUT <i class="bi bi-box-arrow-right"></i></a></li>
                </ul>
            </nav>
        </div>
    </header>

<div class="container">

{% block work %}

    <h2>Admin Dashboard</h2>

    


    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card text-white mb-3">
                <div class="card-header">Jobs</div>
                <div class="card-body">
                    <h5 class="card-title">{{ jobs_count }}</h5>
                      <a href="{% url 'custom_admin:jobs_list' %}" class="btn btn-light btn-sm">View jobs</a>
                  
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card text-white mb-3">
                <div class="card-header">Applications</div>
                <div class="card-body">
                    <h5 class="card-title">{{ apps_count }}</h5>
                    <a href="{% url 'custom_admin:app_list' %}" class="btn btn-light btn-sm">View Applications</a>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card text-white mb-3">
                <div class="card-header">Users</div>
                <div class="card-body">
                    <h5 class="card-title">{{ users_count }}</h5>
                    <a href="{% url 'custom_admin:user_list' %}" class="btn btn-light btn-sm">View Users</a>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}
</body>
</html>

CUSTOM_ADMIN/templates/custom_admin/job_form.html
{% extends "custom_admin/dashboard.html" %}
{% block head %}

<title>JOB FORM</title>

<style>
    .container{
        background-color: rgb(212, 204, 218);
        border: 1px none blueviolet;
        overflow: hidden;
        border-radius: 12px;
    }
</style>
{% endblock %}

{% block work %}
<div class="container">
    <h2 class="mb-3">Job Form</h2>
<form method="POST">
  {% csrf_token %}

<div class="row">
     <div class="col-md-4 mb-3">
            {{ form.title.label_tag }}
            {{ form.title }}
     </div>
      <div class="col-md-4 mb-3">
            {{ form.company.label_tag }}
            {{ form.company }}
     </div>
      <div class="col-md-4 mb-3">
            {{ form.location.label_tag }}
            {{ form.location }}
     </div>
</div>

<div class="row">
     <div class="col-md-6 mb-3">
            {{ form.job_type.label_tag }}
            {{ form.job_type }}
     </div>
      <div class="col-md-6 mb-3">
            {{ form.salary.label_tag }}
            {{ form.salary }}
     </div>
</div>

<div class="row">
     <div class="col-md-6 mb-3">
            {{ form.description.label_tag }}
            {{ form.description }}
     </div>
      <div class="col-md-6 mb-3">
            {{ form.requirements.label_tag }}
            {{ form.requirements }}
     </div>
</div>

  <button type="submit" class="btn btn-success">Save</button>
  <a href="{% url 'custom_admin:jobs_list' %}" class="btn btn-secondary">Cancel</a>
</form>
</div>

{% endblock %}

CUSTOM_ADMIN/templates/custom_admin/job_list.html
{% extends "custom_admin/dashboard.html" %} {% block head %}

<title>JOB LIST</title>

<style>
  .table thead th {
    background-color: rgb(63, 0, 122);
    color: #fff;
  }

  .table{
     border-radius: 12px;        /* Round table corners */
    overflow: hidden;           /* Ensures header/rows follow rounding */
    border: 1px solid #ddd;
    
  }
</style>

{% endblock %} {% block work %}
<div class="d-flex justify-content-between align-items-center mb-3">
  <h2 class="m-0">JOBS</h2>
  <div>
    <a class="btn btn-secondary" href="#">Import CSV</a>
    <a class="btn btn-info" href="#">Export CSV</a>
    <a class="btn btn-success" href="{% url 'custom_admin:job_add' %}"
      >+ Add Job</a
    >
  </div>
</div>

<div class="table-responsive">
  <table class="table table-bordered  table-hover bg-white">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Company</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for job in jobs %}
      <tr>
        <td>{{ job.id }}</td>
        <td>{{ job.title }}</td>
        <td>{{ job.company }}</td>
        <td>
          <a
            class="btn btn-sm btn-primary"
            href="{% url 'custom_admin:job_edit' job.id %}"
            >Edit</a
          >
          <a
            class="btn btn-sm btn-danger"
            href="{% url 'custom_admin:job_del' job.id %}"
            >Delete</a
          >
        </td>
      </tr>

      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

CUSTOM_ADMIN/templates/custom_admin/user_list.html
{% extends 'custom_admin/dashboard.html'%}

{% block head %}
<title>USER LIST</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
      .table thead th{
        background-color: rgb(63, 0, 122);
        color: #fff;
    }

    .table{
     border-radius: 12px;        /* Round table corners */
    overflow: hidden;           /* Ensures header/rows follow rounding */
    border: 1px solid #ddd;
    }
    
</style>
{% endblock %}



{% block work %}
<div class="container mt-4">


    <h3>All Users</h3>
    <div class="table-responsive">
        <table class="table table-bordered table-hover bg-white">
            <thead>
              <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>

              </tr>
            </thead>
           
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>

            </tr>
            {% endfor %}
        </table>
    </div>

</div>
{% endblock %}