JOBFORM/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView
from .views import CustomLoginView
from django.contrib.auth.decorators import login_required

urlpatterns = [

    # ALL JOB POST
    path('job/', login_required(views.job_list), name='job_list'),
    # JOB DETAIL
    path('job/<int:pk>/', login_required(views.job_detail), name='job_detail'),
    path('about/', login_required(views.about), name='about'),
    path('del/<int:pk>/', views.delete, name='delete'),
    path('applications/<int:pk>/pdf/', views.application_pdf, name = 'application_pdf'),



    #ADMIN PAGE
    path('applications/', views.all_applications, name= 'all_applocations'),


    

    # AUTH URLS
    path('signup/', views.signup, name='signup'), 
    path('', RedirectView.as_view(url='/accounts/login/', permanent=False)),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', views.customlogout, name= 'logout'),
 ] 

JOBPROJECT/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from JOBFORM import views


urlpatterns = [
    path('admin/', admin.site.urls),
   path("myadmin/", include("CUSTOM_ADMIN.urls", namespace="custom_admin")),


    path('', include('JOBFORM.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JOBFORM/models.py
from django.db import models

# Create your models here.

GENDER_CHOICES = [
    ('', 'SELECT GENDER'),
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
]

STATE_CHOICES =[
    ('', 'CHOOSE STATES'),
    ('DL', 'Delhi'),
    ('MH', 'Maharashtra'),
    ('KA', 'Karnataka'),
    ('TN', 'Tamil Nadu'),
    ('UP', 'Uttar Pardesh'),
]

JOB_TYPE_CHOICES =[
    ('Full-Time', 'Full-Time'),
    ('Part-Time', 'Part-Time'), 
    ('Remote', 'Remote'),
]



class JobPost(models.Model): 
    title = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    job_type = models.CharField(max_length=50, choices=JOB_TYPE_CHOICES)   
    salary = models.CharField(max_length=20, blank=True)
    description = models.TextField()
    requirements = models.TextField()
    posted_on = models.DateTimeField(auto_now_add=True)

class JobApplication(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE,null = True, blank = True)
    # PERSONAL INFO
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    dob = models.DateField()
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    profile_photo = models.ImageField(upload_to='APPLICANT_PHOTOS/')

    # ADDRESS
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    pincode = models.CharField(max_length=6)

    # EDUCATION
    higest_qualification = models.CharField(max_length=100)
    university_name = models.CharField(max_length=150)
    passing_year = models.IntegerField()

    # EXPERIENCE
    experience = models.FloatField()
    last_company = models.CharField(max_length=150, blank=True, null=True)
    skills = models.CharField(max_length=300)
    resume = models.FileField(upload_to='APPLICANT_RESUMES/')

    # SYSTEM FIELDS
    applied_on = models.DateTimeField(auto_now_add=True)
        

JOBFORM/views.py
from django.shortcuts import redirect, render
from .form import JobApplicationForm, SignupForm,LoginForm
from .models import JobApplication,JobPost
 
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages  
from django.http import HttpResponse
from django.template.loader import render_to_string
from xhtml2pdf import pisa


# Create your views here.
def apply_job(request):

    if request.method == 'POST':
        form = JobApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('admin/')
    else:
        form = JobApplicationForm()

    return render(request, 'job_apply.html', {'form':form})  


# ALL THE APPLICATIONS.............................................................
def all_applications(request):
    form = JobApplication.objects.all().order_by('-applied_on')    
    return render (request, 'all_application.html', {'form':form})

def delete(request,pk):
    form = JobApplication.objects.get(pk=pk)
    form.delete()
    return redirect('/applications/')

def application_pdf(request,pk):
    application = JobApplication.objects.get(pk=pk)

    if application.profile_photo:
        profile_photo_url = request.build_absolute_uri(application.profile_photo.url)

    if application.resume:
        resume_url = request.build_absolute_uri(application.resume.url)

    html = render_to_string("application_pdf.html", {'application':application, "profile_photo_url": profile_photo_url,
        "resume_url": resume_url,})

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="application_{pk}.pdf"'  

    pisa.CreatePDF(html, dest=response)
    return response  
    

# ALL THE JOBS ..........................................................................

@login_required
def job_list(request):
    jobs =  JobPost.objects.all().order_by('-posted_on')
    return render(request, 'job_list.html', {'jobs':jobs}) 

# DETAIL ABOUT THE SPECIFIC JOB AND FORM................................................

@login_required
def job_detail(request,pk):
     job = JobPost.objects.get(pk = pk)
     if request.method == 'POST':
        form = JobApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.job = job
            form.save()
            messages.success(request, "✅ Application submitted for this job!")
            return redirect('/job/')
        else:
               print(form.errors)   # DEBUG
               messages.error(request, f"❌ Failed to apply for this job. Errors: {form.errors}")
     else:
        form = JobApplicationForm()

     return render(request, 'job_detail.html', {'form':form,'job':job})

@login_required
def about(request):
    return render(request,'about.html')

# SIGNUP PAGE...................................................................
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignupForm()
    return render(request,'registration/signup.html', {'form':form})    



def customlogout(request):
    logout(request)
    return redirect('login')

class CustomLoginView(LoginView):
    authentication_form = LoginForm 
    template_name = 'registration/login.html'

JOBFORM/templates/about.html
{% extends 'master.html' %}


{% block head %}
<title>About | InsideJob</title>
{% endblock %}
{% block work %}

<style>
    .about-container {
        max-width: 700px;
        margin: 210px auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 10px;
        text-align: center;
        box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.1);
        font-family: Arial, sans-serif;
         background: rgba(0, 0, 0, 0.5);

    }

    .about-container h2 {
        color: red;
        margin-bottom: 15px;
        border-bottom: red solid 1px;
       
    }

    .about-container p {
        color: #fff;
        line-height: 1.6;
        margin-bottom: 10px;
    }
</style>

<div class="about-container">
    <h2>About Us</h2>
    <p>
        Welcome to our Job Portal. We connect skilled professionals with top IT 
        and tech industry employers.
    </p>
    <p>
        Our mission is to make job hunting simple, fast, and effective for both 
        job seekers and recruiters.
    </p>
</div>
{% endblock %}

JOBFORM/templates/all_application.html
{% extends 'master.html'%}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    .container {

        text-align: center;
        justify-content: space-between;
        
       
        gap: 20px;
        max-width: 1100px;
        background: #fff;
        overflow-y: auto;
        text-transform: uppercase;
        
    }

    .container th {
        color: red;
    }
  
</style>
{% endblock %}



    

{% block work %}

<h2>All Applications</h2>
<div class="container ">
    <table class="table table-bordered table-striped mt-3">
        <thead>
            <tr>
                <th>PHOTO</th>
                <th>NAME</th>
                <th>JOB</th>
                
                <th>APPLIED ON</th>
                <th>INFO</th>
                <th>RESUME</th>
                <th>DELETE</th>

            </tr>
        </thead>
        <tbody>
            {% for x in form %}
            <tr>
                <td>{% if x.profile_photo %}
                    <a href="{{x.profile_photo.url}}" download> <img src="{{x.profile_photo.url}}" width="50"
                            height="50" download> </a>
                    {% else %}
                    No File
                    {% endif %}
                </td>
                <td>{{x.full_name}}</td>
                <td>{{x.job.title}}</td>
                
                <td>{{x.applied_on}}</td>

                <td>{% if x.resume %}
                    <a href="{{x.resume.url}}" download> INFO </a>
                    {% else %}
                    No File
                    {% endif %}</td>

                <td> 
                    <a href="/applications/{{x.pk}}/pdf/">DOWNLOAD</a>
                </td>
                <td><a class="btn btn-danger" href="/del/{{x.pk}}">DELETE</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>







{% endblock %}

JOBFORM/templates/application_pdf.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">

    <title>Job Application PDF</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
            text-transform: uppercase;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            text-transform: uppercase;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 9px;
            text-align: center;
            align-items: center;
            justify-content: center;
            text-transform: uppercase;
            text-align: left;
            font-size: 12px;
        }

        th {
            background: #f2f2f2;
        }

        h2,
        h3 {
            margin-top: 15px;
            color: #333;
        }

        img {
            max-width: 155px;
            height: 120px;
        }
       
    </style>
</head>

<body>
    <h2>Job Application</h2>

    <!-- Personal Info -->
    <h3>Personal Information</h3>
    <table>
        <tr>
            <th>Full Name</th>
            <td>{{ application.full_name }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ application.email }}</td>
        </tr>
        <tr>
            <th>Phone</th>
            <td>{{ application.phone }}</td>
        </tr>
        <tr>
            <th>Date of Birth</th>
            <td>{{ application.dob }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{{ application.gender }}</td>
        </tr>
        <tr>
            <th>Profile Photo</th>
            <td id="img">
                {% if profile_photo_url %}
               <img src="{{profile_photo_url }}" alt="Profile Photo">

                {% else %}
                No photo uploaded
                {% endif %}
            </td>
        </tr>
    </table>

    <!-- Address -->
    <h3>Address</h3>
    <table>
        <tr>
            <th>Address</th>
            <td>{{ application.address }}</td>
        </tr>
        <tr>
            <th>City</th>
            <td>{{ application.city }}</td>
        </tr>
        <tr>
            <th>State</th>
            <td>{{ application.get_state_display }}</td>
        </tr>
        <tr>
            <th>Pincode</th>
            <td>{{ application.pincode }}</td>
        </tr>
    </table>

    <!-- Education -->
    <h3>Education</h3>
    <table>
        <tr>
            <th>Highest Qualification</th>
            <td>{{ application.higest_qualification }}</td>
        </tr>
        <tr>
            <th>University</th>
            <td>{{ application.university_name }}</td>
        </tr>
        <tr>
            <th>Passing Year</th>
            <td>{{ application.passing_year }}</td>
        </tr>
    </table>

    <!-- Experience -->
    <h3>Experience</h3>
    <table>
        <tr>
            <th>Years of Experience</th>
            <td>{{ application.experience }}</td>
        </tr>
        <tr>
            <th>Last Company</th>
            <td>{{ application.last_company }}</td>
        </tr>
       
        
           
    </table>
</body>

</html>

JOBFORM/templates/job_apply.html
{% extends 'master.html'%}


  {% block head %}
          
  {% endblock %}

{% block work %}
<h1>apply</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">SUBMIT</button>
</form>

{% endblock %}

JOBFORM/templates/job_detail.html
{% extends 'master.html'%}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<title>Form | InsideJob</title>
<style>
    .job-container {
        display: flex;
        flex-wrap: wrap; 
        gap: 30px;
        margin-top: 50px;
    }

    .column1,
    .column2 {
        flex: 1 1 48%; 
        padding: 25px;
        border: 1px solid #ccc;
        border-radius: 12px;
         background: #fff;
        
    }

    /* Job Details Styling */
.column1 h2 {
    font-size: 2rem;
    font-weight: 700;
    color: #d92323; /* red accent */
    margin-bottom: 15px;
}

.column1 p {
    font-size: 1rem;
    margin-bottom: 10px;
    color: #444;
}

/* Salary emphasis */
.column1 h4 {
    margin-top: 20px;
    color: #111;
    font-weight: bold;
}

/* Apply Form Styling */
.column2 h2 {
    font-size: 2rem;
    font-weight: 700;
    margin-bottom: 20px;
    color: red;
    border-bottom: 2px solid #d92323;
    padding-bottom: 10px;
}

.column2 form {
    display: flex;
    flex-direction: column;
    gap: 15px;
}

.column2 button {
    
    padding: 10px 20px;
    font-weight: 600;
}



   
</style>
{% endblock %}

{% block work %}

<!-- JOB DETAILS + APPLY FORM -->
<div class="container job-container">

    <!-- Left Column: Job Info -->
    <div class="column1">
        <h2 style="border-bottom: 2px solid red;">{{ job.title }}</h2>
        <p><strong>Company:</strong> {{ job.company }}</p>
        <p><strong>Location:</strong> {{ job.location }}</p>
        <p><strong>Type:</strong> {{ job.job_type }}</p>
        <p><strong>Description:</strong> {{ job.description }}</p>
        <p><strong>Posted on:</strong> {{ job.posted_on}}</p>
        <h4><strong>Salary:</strong> {{ job.salary }}</h4>
    </div>

    <!-- Right Column: Form -->
     <div class="column2">
        <h2>Apply Now</h2>
        <form method="POST" enctype="multipart/form-data" class="p-4 shadow rounded bg-light">
    {% csrf_token %}

    <!-- Personal Info -->
    <h4 class="mb-3" style="color: red;">Personal Information:</h4>
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form.full_name.label_tag }}
            {{ form.full_name }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form.phone.label_tag }}
            {{ form.phone }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form.dob.label_tag }}
            {{ form.dob }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form.gender.label_tag }}
            {{ form.gender }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form.profile_photo.label_tag }}
            {{ form.profile_photo }}
        </div>
    </div>

    <!-- Education -->
    <h4 class="mt-4 mb-3" style="color: red;">Education:</h4>
    <div class="row">
        <div class="col-md-4 mb-3">
            {{ form.higest_qualification.label_tag }}
            {{ form.higest_qualification }}
        </div>
        <div class="col-md-4 mb-3">
            {{ form.university_name.label_tag }}
            {{ form.university_name }}
        </div>
        <div class="col-md-4 mb-3">
            {{ form.passing_year.label_tag }}
            {{ form.passing_year }}
        </div>
    </div>

     <h4 class="mt-4 mb-3" style="color: red;">Address:</h4>
    <div class="row">
        <div class="col-md-4 mb-3">
            {{ form.city.label_tag }}
            {{ form.city }}
        </div>
        <div class="col-md-4 mb-3">
            {{ form.state.label_tag }}
            {{ form.state }}
        </div>
        <div class="col-md-4 mb-3">
            {{ form.pincode.label_tag }}
            {{ form.pincode }}
        </div>
         <div class="col-md-12 mb-3">
            {{ form.address.label_tag }}
            {{ form.address }}
        </div>
    </div>

    <!-- Work Experience -->
    <h4 class="mt-4 mb-3" style="color: red;">Work Experience:</h4>
    <div class="row">
        <div class="col-md-6 mb-3">
            {{ form.experience.label_tag }}
            {{ form.experience }}
        </div>
        <div class="col-md-6 mb-3">
            {{ form.last_company.label_tag }}
            {{ form.last_company }}
        </div>
        <div class="col-md-12 mb-3">
            {{ form.resume.label_tag }}
            {{ form.resume }}
        </div>
    </div>

    <button type="submit" class="btn btn-danger w-100">Submit Application</button>
</form>
       
    </div>

</div> 
 

{% endblock %}

JOBFORM/templates/job_list.html
{% extends 'master.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'job_list.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<title>JobList | InsideJob</title>
<style>
  .job-container {
    display: grid;
    gap: 20px;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    margin-top: 50px;
    justify-content: space-between;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
  }

  .column {

    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    background: #fff;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
     
  }

  .column:hover{
    
   border-color: red;
  }

  .card {
    display: flex;

  }

  .banner {
    background: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)),
    url("{% static 'images/bg_home.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    height: 87.5vh;
    display: flex;
    align-items: center;

    justify-content: center;
    text-align: center;
    border-bottom: 4px solid red;

  }

  .content {
    background: rgba(0, 0, 0, 0.5);
    padding: 2rem 3rem;
    border: 3px double red;
    border-radius: 12px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);

  }

  .content h1 {
    font-size: 3rem;
    margin-bottom: 1rem;
    color: #ddd;
  }

  .content p {
    font-size: 1.2rem;
    margin-bottom: 2rem;
    color: #ddd;
  }

  .date {
    display: inline-block;
    background: #f8f9fa;
    color: #333;
    padding: 4px 10px;
    border-radius: 50px;
    font-size: 0.75rem;
    margin-bottom: 10px;


  }
</style>
{% endblock %}

{% block work %}

<section class="banner">
  <div class="content">
    <h1> “Where Talent Meets Opportunity.”</h1>
    <p> “Discover the best IT jobs, connect with leading companies, and grow your career.”</p>
    <a href="#jobs" class="btn btn-danger">BROWSE JOBS</a>
  </div>
</section>

<div class="container" style="margin-top: 0px;" id="jobs">
 <h1 class="my-3 text-center fw-bold" style="color: #222;">Available IT Job Posts</h1>

  <div class="job-container">
    {% for job in jobs %}
    <div class="column">

      <p class="date">{{job.posted_on}}</p>
      <h2>{{ job.title }}</h2>
      <p><strong>Company:</strong> {{ job.company }}</p>
      <p><strong>Location:</strong> {{ job.location }}</p>
      <p><strong>Type:</strong> {{ job.job_type }}</p>
      <a href="/job/{{ job.id }}" class="btn btn-danger mt-auto">View & Apply</a>

    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

JOBFORM/templates/master.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'job_list.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">



    {% block head %}
    <title></title>
    {% endblock %}

</head>

<style>
    html,
    body {
        height: 100%;
         margin: 0;           /* remove default margin */
    display: flex;
    flex-direction: column;
    }
    main{
        flex: 1;
    }

  
    header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 1rem 2rem;
        background-color: black;
        border-bottom: 3px solid red;
        position: sticky;
        top: 0;
        z-index: 1000;
    }

    .logo {
        color: red;
        font-weight: 700;
        font-size: 1.8rem;
        letter-spacing: 1px;
    }

    .job-head nav ul {
        list-style: none;
        display: flex;
        gap: 1.5rem;
        margin: 0;
        padding: 0;
    }

    .job-head nav a {
        text-decoration: none;
        font-weight: 500;
        color: white;
        transition: color 0.3s ease;
    }

    .job-head nav a:hover {
        color: red;
    }

    .job-head nav .btn:hover {
        color: black;
    }

    /* Make logout consistent */
    .job-head nav .btn {
        padding: 0.4rem 0.9rem;
        border-radius: 20px;
        font-size: 0.9rem;
    }





    body {
        background:  linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)),url("{% static 'images/bg_about.jpg' %}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
        display: flex;
        flex-direction: column;
    }



    footer {
        text-align: center;
        border-top: 4px double red;
        background-color: black;
        margin-bottom: 0%;
        padding: 0.8rem 1.1rem;
        color: red;
        margin-top: 10px;

    }
</style>
</head>



<body>
    <header class="job-head">
        <div class="logo"> INSIDE JOB</div>
        <div class="navbar">
            <nav>
                <ul>
                    <li><a href="/job/">HOME</a></li>
                    <li><a href="/about/">ABOUT</a></li>
                    <li><a class="btn btn-outline-danger ms-3" href="/logout/">
                        LOGOUT <i class="bi bi-box-arrow-right"></i></a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <main>
    {% if messages %}
      <div class="container mt-3">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      </div>
    {% endif %}
        {% block work %}
        {% endblock %}
    </main>

    <footer>
        <div>
            <h3>JobHub</h3>
            <p>Your destination for top IT jobs in India</p>
            <p>&copy; 2025 INSIDE JOB. All rights reserved.</p>
        </div>
    </footer>
</body>


</html>